@extends('vendor.shopify-app.layouts.default')
@section('content')
<style>
.icon {
  position: absolute;
  top: -11px;
  right: -10px;
  transform: translate(-50%,-50%);
  width: 80px;
  height: 60px;
  cursor: pointer;
  transform : scale(0.3);

}
.icon2{
  position: absolute;
  top: -11px;
  right: -10px;
  transform: translate(-50%,-50%);
  width: 80px;
  height: 60px;
  cursor: pointer;
  transform : scale(0.3);

}

.arrow {
  position: absolute;
  top: 25px;
  width: 90%;
  height: 8px;
  background-color: #fff;
  box-shadow: 0 3px 5px rgba(0, 0, 0, .2);
  animation: arrow 700ms linear infinite;
}
.arrow2{
  position: absolute;
  top: 25px;
  width: 90%;
  height: 8px;
  background-color: #fff;
  box-shadow: 0 3px 5px rgba(0, 0, 0, .2);
  animation: arrow 700ms linear infinite;
}

.arrow::after, .arrow::before {
  content: '';
  position: absolute;
  width: 60%;
  height: 8px;
  right: -8px;
  background-color: #fff;
}

.arrow2::after, .arrow2::before {
  content: '';
  position: absolute;
  width: 60%;
  height: 8px;
  right: -8px;
  background-color: #fff;
}
.arrow::after {
  top: -12px;
  transform: rotate(45deg);
}
.arrow2::after {
  top: -12px;
  transform: rotate(45deg);
}


.arrow::before {
  top: 12px;
  box-shadow: 0 3px 5px rgba(0, 0, 0, .2);
  transform: rotate(-45deg);
}
.arrow2::before {
  top: 12px;
  box-shadow: 0 3px 5px rgba(0, 0, 0, .2);
  transform: rotate(-45deg);
}
.button-div{
	position: absolute;
	right: 0px;
	background-color: #0e2059 ;
	width: 225px;
	padding: 5px 15px;
	height: 40px;
	color: white;
	text-align: left;
	font-size: 15px;
	display: inline-flex;
	align-items: center;
	border-radius: 10px;

}
.text-button-div{
	text-decoration: none;
	color: white;


}
</style>

   <div class="container">
		<div class="col-md-12 upsel_price">
			<h2>Welcome to Alpha Upsell Suite-Important Message <span>
					<a href="{{ route('billing', ['plan' => $plan_id]) }}">
					   <div class="button-div">
						<div class="text-button-div">
							Get Started for FREE
						</div>
						<div class="icon"><div class="arrow"></div></div>
                        </div>
					</a>
				</span></h2>
			<div class="price_p">
				<p>Congratulations, you are 5 minutes away from <span>boosting your revenue by up to 15%!</span></p>
				<p>In the next page, you will approve charges for the highest possible plan (up to $349.99/monthly).</p>
				<p><span>Pricing is based on the total orders in the store, not generated by the app.</span></p>
				<p>The app is 100% FREE if you have less than 50 order/month.</p>
				{{-- and you get a 30 days free trial either way --}}
			</div>
			<div class="price_table">
				<table width="100%" border="0" class="table table-striped table-bordered table_dash table-responsive">
					<tbody>
						<tr class="table_head_price">
							<th>Orders Per Month</th>
							<th>Features</th>
							<th>Price</th>
						</tr>
						<tr>
							<td>0 - 50</td>
							<td>Full Features</td>
							<td>Free</td>
						</tr>
						<tr>
							<td>51 - 100</td>
							<td>Full Features</td>
							<td>$7.99</td>
						</tr>
						<tr>
							<td>101 - 200</td>
							<td>Full Features</td>
							<td>$14.99</td>
						</tr>
						<tr>
							<td>201 - 500</td>
							<td>Full Features</td>
							<td>$29.99</td>
						</tr>
						<tr>
							<td>501 - 1,000</td>
							<td>Full Features</td>
							<td>$49.99</td>
						</tr>
						<tr>
							<td>1,001 - 2,000</td>
							<td>Full Features</td>
							<td>$89.99</td>
						</tr>
						<tr>
							<td>2.001 - 5,000</td>
							<td>Full Features</td>
							<td>$139.99</td>
						</tr>
						<tr>
							<td>5,001 - 10,000</td>
							<td>Full Features</td>
							<td>$169.99</td>
						</tr>
						<tr>
							<td>10,001 - 20,000</td>
							<td>Full Features</td>
							<td>$199.99</td>
						</tr>
						<tr>
							<td>20,001 - 50,000</td>
							<td>Full Features</td>
							<td>$249.99</td>
						</tr>
						<tr>
							<td>50,001 - 100,000</td>
							<td>Full Features</td>
							<td>$349.99</td>
						</tr>
						<tr>
							<td>100,000 +</td>
							<td>Full Features</td>
							<td>Contact us</td>
						</tr>
					</tbody>
				</table>
			</div>
			<div class="price_btn">
				<a href="{{ route('billing', ['plan' => $plan_id]) }}">
                    <div class="button-div">
                    <div class="text-button-div">
                        Get Started for FREE
                    </div>
                    <div class="icon2"><div class="arrow2"></div></div>
                    </div>
				</a>
			</div>
		</div>
	</div>

<script>
const $icon = document.querySelector('.icon');
const $arrow = document.querySelector('.arrow');


  $arrow.animate([
    {left: '0'},
    {left: '10px'},
    {left: '0'}
  ],{
    duration: 700,
    iterations: Infinity
  });

const $icon2 = document.querySelector('.icon2');
const $arrow2 = document.querySelector('.arrow2');


console.log($icon2);
console.log($arrow2);


  $arrow2.animate([
    {left: '0'},
    {left: '10px'},
    {left: '0'}
  ],{
    duration: 700,
    iterations: Infinity
  });

</script>
@endsection
@push('componentCss')
    <!-- Global site tag (gtag.js) - Google Ads: 561514405 -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=AW-561514405"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'AW-561514405');
    </script>
    <!-- Event snippet for ALPHA Upsell Suite Installed conversion page -->
    <script>
        gtag('event', 'conversion', {
            'send_to': 'AW-561514405/DpodCL325oADEKWP4IsC',
            'value': 1.0,
            'currency': 'USD'
        });
    </script>
@endpush



