<?php

use Carbon\Carbon;
return [
    // constant string used in the app
    'strings' => [
        'upsellTypes' => [
            [
                'name'      => explode(',',env('UPSELLTYPE_NAMES_TO_MATCH'))[0],
                'image'     => '/img/icon_1.png',
                'setting'   => [
                    'location_of_fbt'               => 'below_add_to_cart',
                    'work_on_desktop'               => 1,
                    'work_on_mobile'                => 1,
                    'fbt_heading'                   => "Frequently Bought Together",
                    'heading_font_family'           => "Sans-Serif",
                    'heading_font_size'             => 22,
                    'heading_color'                 => "#251c6bff",
                    'heading_align'                 => "left",
                    'button_text'                   => "Add Selected To Cart",
                    "this_item"                     => "This item",
                    'sale_badge_text'               => "Sale",
                    'total_price_text'              => "Total Price",
                    'product_title_color'           => "#fb0000ff",
                    'sale_price_color'              => "#00aedaff",
                    'compare_price_color'           => "#546ea9ff",
                    'button_border_color'           => "#546ea9ff",
                    'button_text_color'             => "#f9f9f9ff",
                    'button_hover_text_color'       => "#824b4bff",
                    'button_background_color'       => "#546ea9ff",
                    'button_hover_background_color' => "#a7b5d6ff",
                    'show_original_total_price'     => 1,
                    'show_compare_price_available'  => 1,
                    'show_sale_badge_on_image'      => 1,
                ],
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
                'templates' => []
            ],
            [
                'name'      => explode(',',env('UPSELLTYPE_NAMES_TO_MATCH'))[1],
                'image'     => '/img/pre_purchase.png',
                'setting'   => [
                    'discount_type'                 => '% Off',
                    'discount_value'                => 10,
                    'work_on_desktop'               => 1,
                    'work_on_mobile'                => 1,
                ],
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
                'templates' => [
                    [
                        'name' => 'add_to_cart_template1',
                        'template_path' => 'string',
                        'setting'   => [
                            'add_to_cart_heading'           => "Added To Your Bag",
                            'heading_font_family'           => "Sans-Serif",
                            'heading_font_size'             => 19,
                            'heading_color'                 => "#000000ff",
                            'heading_align'                 => "Left",
                            'heading_background_color'      => "#e8e8e8ff",
                            'cross_icon_color'              => "#f34d00ff",
                            'total_price_text'              => "Total:",
                            'text-color-price-total'        => '#448ea1ff',
                            'price-color-figure'            => '#000000ff',
                            'offer_time_limit'              => 1,
                            "time_offer_heading"            => "Limited Time Offer",
                            'offer_heading_font_family'     => "Sans-Serif",
                            'offer_heading_font_size'       => 14,
                            'time_duration_minutes'         => 10,
                            'timer_text'                    => "Time Left",
                            'time_offer_heading_color'      => "#f34d00ff",
                            'timer_heading_color'           => "#525252ff",
                            'timer_color'                   => "#f34d00ff",
                            'add_to_cart_text'              => "Add To Cart",
                            'Original_price_color'          => "#f34d00ff",
                            'button_background_color'       => "#f34d00ff",
                            'discount_background_color'     => "#242424ff",
                            'button_text_color'             => "#F0F0F0ff",
                            'discount_text_color'           => "#F0F0F0ff",
                            'checkout_button_text'          => "Checkout",
                            'no_thanks_button_text'         => "No Thanks",
                            'checkout_background_color'     => "#000000ff",
                            'no_thanks_background_color'    => "#f6f6f6ff",
                            'checkout_text_color'           => "#ffffffff",
                            'no_thanks_text_color'          => "#000000ff",
                            'checkout_border_color'         => "#000000ff",
                            'no_thanks_border_color'        => "#f34d00ff",

                        ]
                    ],
                    [
                        'name' => 'add_to_cart_template2',
                        'template_path' => 'string',
                        'setting'   => [
                            'top_heading'                   => 'You Just Added',
                            'top_heading_font_family'       => "Sans-Serif",
                            'top_heading_font_size'         => 15,
                            'top_heading_color'             => "#000000ff",
                            'top_heading_bg_color'          => "#eaf7f3ff",
                            'cross_icon_color'              => "#ffffffff",
                            't2-total-price-text'           => "Total:",
                            't2-total-price-color'          => '#3bbb92ff',
                            't2-price-color'                => '#000000ff',
                            'cross_icon_bg_color'           => "#3bbb92ff",
                            'qty_selctor_border_color'      => "#3bbb92ff",
                            'offer_time_limit'              => 1,
                            'offer_heading'                 => "Complete Your Look With Our Deals At",
                            'offer_span'                    => "10% Discount!!",
                            'offer_heading_font_family'     => "Sans-Serif",
                            'offer_heading_font_size'       => 16,
                            'time_duration_minutes'         => 10,
                            "time_offer_heading"            => "Time Left",
                            'timer_heading_font_family'     => "Sans-Serif",
                            'timer_heading_font_size'       => 13,
                            'offer_heading_color'           => "#3bbb92ff",
                            'offer_span_color'              => "#1275baff",
                            'timer_heading_color'           => "#525252ff",
                            'timer_color'                   => "#3bbb92ff",
                            'add_to_cart_text'              => "Add To Cart",
                            'atc_background_color'          => "#3bbb92ff",
                            'atc_text_color'                => "#ffffffff",
                            'Original_price_color'          => "#3bbb92ff",
                            'discount_background_color'     => "#4A4A4Aff",
                            'discount_text_color'           => "#F0F0F0ff",
                            'checkout_button_text'          => "Checkout",
                            'no_thanks_button_text'         => "No Thanks",
                            'checkout_background_color'     => "#3bbb92ff",
                            'no_thanks_background_color'    => "#f8f8f8ff",
                            'checkout_text_color'           => "#ffffffff",
                            'no_thanks_text_color'          => "#292929ff",
                            'checkout_border_color'         => "#3bbb92ff",
                            'no_thanks_border_color'        => "#3bbb92ff",
                        ]
                    ],
                    [
                        'name' => 'add_to_cart_template3',
                        'template_path' => 'string',
                        'setting'   => [
                            'top_heading'                   => 'Item Added To Your Cart',
                            'top_heading_font_family'       => "Sans-Serif",
                            'top_heading_font_size'         => 16,
                            'top_heading_color'             => "#000000ff",
                            'cross_icon_color'              => "#F0F0F0ff",
                            'cross_icon_bg_color'           => "#44a5ffff",
                            'cart_product_bg_color'         => "#f5f5f5ff",
                            'cart_product_border_color'     => "#44a5ffff",
                            'cart_product_price_color'      => "#44a5ffff",
                            'continue_shoping_btn_color'    => "#292929ff",
                            'offer_time_limit'              => 1,
                            'offer_heading'                 => "You May Be Interested In...",
                            'offer_heading_font_family'     => "Sans-Serif",
                            'offer_heading_font_size'       => 16,
                            'time_duration_minutes'         => 10,
                            "time_offer_heading"            => "Ends Soon",
                            'time_offer_font_family'        => "Sans-Serif",
                            'time_offer_font_size'          => 15,
                            'offer_heading_color'           => "#393939ff",
                            'timer_heading_color'           => "#44a5ffff",
                            'timer_color'                   => "#EDEDEDff",
                            'timer_bg_color'                => "#292929ff",
                            'add_to_cart_text'              => "Add To Cart",
                            'atc_background_color'          => "#44a5ffff",
                            'atc_text_color'                => "#ffffffff",
                            'Original_price_color'          => "#000000ff",
                            'discount_background_color'     => "#44a5ffff",
                            'discount_text_color'           => "#ffffffff",
                            'product_bg_color'              => "#F0F0F0ff",
                            'checkout_button_text'          => "Checkout",
                            'no_thanks_button_text'         => "No Thanks",
                            'checkout_background_color'     => "#44a5ffff",
                            'no_thanks_background_color'    => "#ffffffff",
                            'checkout_text_color'           => "#ffffffff",
                            'no_thanks_text_color'          => "#000000ff",
                            'checkout_border_color'         => "#44a5ffff",
                            'no_thanks_border_color'        => "#44a5ffff",
                        ]
                    ],
                    [
                        'name' => 'add_to_cart_template4',
                        'template_path' => 'string',
                        'setting'   => [
                            'offer_time_limit'                  => 1,
                            'time_duration_minutes'             => 10,
                            "time_offer_heading"                => "Deal Ends Soon:",
                            'time_offer_font_family'            => "Sans-Serif",
                            'time_offer_font_size'              => 15,
                            'timer_heading_color'               => "#000000ff",
                            'timer_color'                       => "#ffffffff",
                            'timer_bg_color'                    => "#de5c5cff",
                            'cross_icon_color'                  => "#ffffffff",
                            'cross_icon_bg_color'               => "#6B6B6Bff",
                            'cart_product_bg_color'             => "#f5f5f5ff",
                            'cart_cross_icon_bg_color'          => "#de5c5cff",
                            'cart_product_price_color'          => "#de5c5cff",
                            'cart_product_checkout_text_color'  => "#E9E9E9ff",
                            'offer_heading'                     => "Check out these items we think you would love!",
                            'offer_heading_font_family'         => "Sans-Serif",
                            'offer_heading_font_size'           => 16,
                            'offer_heading_color'               => "#000000ff",
                            'add_to_cart_text'                  => "Get It Now",
                            'atc_background_color'              => "#de5c5cff",
                            'atc_text_color'                    => "#D9D9D9ff",
                            'Original_price_color'              => "#de5c5cff",
                            'discount_background_color'         => "#6B6B6Bff",
                            'discount_text_color'               => "#ffffffff",
                            'checkout_button_text'              => "Checkout",
                            'no_thanks_button_text'             => "No Thanks",
                            'checkout_background_color'         => "#6B6B6Bff",
                            'no_thanks_background_color'        => "#f8f8f8ff",
                            'checkout_text_color'               => "#ffffffff",
                            'no_thanks_text_color'              => "#6B6B6Bff",
                            'checkout_border_color'             => "#6B6B6Bff",
                            'no_thanks_border_color'            => "#6B6B6Bff",
                        ]
                    ],
                    [
                        'name' => 'add_to_cart_template5',
                        'template_path' => 'string',
                        'setting'   => [
                            'offer_time_limit'                  => 1,
                            'time_duration_minutes'             => 10,
                            "time_offer_heading"                => "Wait! Don't miss our special deal:",
                            'time_offer_font_family'            => "Sans-Serif",
                            'time_offer_font_size'              => 16,
                            'timer_heading_color'               => "#393939ff",
                            'timer_color'                       => "#F4F4F4ff",
                            'timer_bg_color'                    => "#626262ff",
                            'cross_icon_color'                  => "#13a1cfff",
                            'cart_product_bg_color'             => "#e8f8edff",
                            'cart_product_price_color'          => "#13a1cfff",
                            'add_to_cart_text'                  => "Add",
                            'atc_background_color'              => "#13a1cfff",
                            'atc_border_color'                  => "#13a1cfff",
                            'atc_text_color'                    => "#ffffffff",
                            'original_price_color'              => "#13a1cfff",
                            'discount_background_color'         => "#13a1cfff",
                            'discount_text_color'               => "#ffffffff",
                            'checkout_button_text'              => "Continue To Checkout",
                            'no_thanks_button_text'             => "No Thanks",
                            'checkout_background_color'         => "#13a1cfff",
                            'no_thanks_background_color'        => "#ffffffff",
                            'checkout_text_color'               => "#F5F5F5ff",
                            'no_thanks_text_color'              => "#13a1cfff",
                            'checkout_border_color'             => "#13a1cfff",
                            'no_thanks_border_color'            => "#13a1cfff",
                        ]
                    ],
                    [
                        'name' => 'add_to_cart_template6',
                        'template_path' => 'string',
                        'setting'   => [
                            "top_heading"                       => "Check out these items we think you would love!",
                            'top_heading_font_family'           => "Sans-Serif",
                            'top_heading_font_size'             => 16,
                            'timer_heading_color'               => "#000000ff",
                            'cross_icon_color'                  => "#F0F0F0ff",
                            'cross_icon_bg_color'               => "#cc780bff",
                            'cart_product_title_color'          => "#cc780bff",
                            'cart_product_bg_color'             => "#eeeeeeff",
                            'cart_product_price_color'          => "#cc780bff",
                            "offer_heading"                     => "You May Be Interested In...",
                            'add_to_cart_text'                  => "Add To Cart",
                            "offer_heading_color"               => "#cc780bff",
                            'orignal_price_color'               => "#434242ff",
                            'discount_background_color'         => "#cc780bff",
                            'discount_text_color'               => "#F1F1F1ff",
                            'atc_background_color'              => "#434242ff",
                            'atc_border_color'                  => "#434242ff",
                            'atc_text_color'                    => "#EDEDEDff",
                            'checkout_button_text'              => "Checkout",
                            'no_thanks_button_text'             => "No Thanks",
                            'checkout_background_color'         => "#434242ff",
                            'no_thanks_background_color'        => "#F5F5F5ff",
                            'checkout_text_color'               => "#ffffffff",
                            'no_thanks_text_color'              => "#cc780bff",
                            'checkout_border_color'             => "#eff0f0ff",
                            'no_thanks_border_color'            => "#eff0f0ff",
                        ]
                    ],
                ]
            ],
            [
                'name'      => env('UPSELLTYPE_IN_CART'),
                'image'     => '/img/icon_2.png',
                'setting'   => [

                    'work_on_desktop'               => 1,
                    'work_on_mobile'                => 1,
                    'incart_heading'                => "15% OFF! Timer until the offer expires",
                    'heading_font_family'           => "Sans-Serif",
                    'heading_font_size'             => 22,
                    'heading_color'                 => "#ff3f3fff",
                    'heading_align'                 => "left",
                    'count_down_timer'              => 1,
                    "time_duration_minutes"         => 10,
                    'timer_font_family'             => "Sans-Serif",
                    'timer_font_size'               => 22,
                    'button_text'                   => "Add To Cart",
                    'show_product_title'            => 1,
                    'show_variant_selection'        => 1,
                    'show_compare_price'            => 1,
                    'product_title_color'           => "#000000ff",
                    'upsell_background_color'       => "#dee3e5ff",
                    'sale_price_color'              => "#00aedaff",
                    'timer_text_color'              => "#ffffffff",
                    'timer_text_bg_color'           => "#4287f5ff",
                    'compare_price_color'           => "#546ea9ff",
                    'button_border_color'           => "#546ea9ff",
                    'button_text_color'             => "#ffffffff",
                    'button_hover_text_color'       => "#824b4bff",
                    'button_background_color'       => "#546ea9ff",
                    'button_hover_background_color' => "#a7b5d6ff",

                ],
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
                'templates' => []
            ],
            [
                'name'      => env('UPSELLTYPE_POST_PURCHASE'),
                'image'     => '/img/thank_you.png',
                'setting'   => [
                    'work_on_desktop'               => 1,
                    'work_on_mobile'                => 1,
                    'ppu_heading'                   => "You've unlocked a special offer..!!",
                    'heading_font_family'           => "Sans-Serif",
                    'heading_font_size'             => 16,
                    'heading_color'                 => "#251c6bff",
                    'heading_align'                 => "center",
                    'time_limit'                    => 1,
                    'timer_duration'                => 10,
                    'thank_you_timer_text'          => "Offer Ends Soon:",
                    'thank_you_timer_text_color'    => "#ffffffff",
                    'thank_you_timer_text_bg_color' => "#b00000ff",
                    'thank_you_timer_color'         => "#ffffffff",
                    'timer_font_family'             => "Sans-Serif",
                    'timer_font_size'               => 15,
                    'button_text'                   => "Add To Cart",
                    'show_product_title'            => 1,
                    'show_varient_selection'        => 1,
                    'show_compare_price'            => 1,
                    'upsell_discount_type'          => "% Off",
                    'upsell_discount'               => 10,
                    'product_title_color'           => "#060063ff",
                    'upsell_background_color'       => "#D4D4D4ff",
                    'sale_price_color'              => "#1f1f1fff",
                    'discount_text_color'           => "#edededff",
                    'discount_background_color'     => "#00d10eff",
                    'button_border_color'           => "#546ea9ff",
                    'button_text_color'             => "#dadadaff",
                    'button_hover_text_color'       => "#c2c2c2ff",
                    'button_background_color'       => "#03004aff",
                    'button_hover_background_color' => "#02002eff",
                    'arrow_icon_color'              => '#ffffffff',
                    'arrow_icon_background_color'   => '#015d75ff'

                ],
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
                'templates' => []
            ],
            [
                'name'      => env('SALE_NOTIFICATION_IDENTIFIER'),
                'image'     => '/img/icon_5.png',
                'setting'   => [
                    'layout_type'                             => 'Rectangle Notification',
                    'initial_notification_display_time'       => 10,
                    'delay_time_between_notification'         => 5,
                    'animation_type'                          => 'Fade In',
                    'repeat_cycle'                            => 0,
                    'hide_on_mobile'                          => 1,
                    'pop_up_position'                         => 'Bottom Left',
                    'product_title_font_size'                 => 14,
                    'text_font_size'                          => 16,
                    'product_title_weight'                    => 'Normal',
                    'text_weight'                             => 'Bold',
                    'product_title_color'                     => '#321d77ff',
                    'background_color'                        => '#f5f0f0ff',
                    'timer_color'                             => '#d70003ff',
                    'text_color'                              => '#00ccffff',
                    'cross_icon_color'                        => '#0a0909ff',
                    'cross_icon_background_color'             => '#e6e1e1ff',
                    'start_date'                              => '',
                    'end_date'                                => '',
                ],
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
                'templates' => []
            ],
            [
                'name'      => explode(',',env('UPSELLTYPE_NAMES_TO_MATCH'))[2],
                'image'     => '/img/icon_6.png',
                'setting'   => [
                    'work_on_desktop'               => 1,
                    'work_on_mobile'                => 1,
                    'volume_discount_heading'       => "Bulk Buy Offers Unlocked",
                    'heading_font_family'           => "Sans-Serif",
                    'heading_font_size'             => 22,
                    'heading_color'                 => "#251c6bff",
                    'heading_align'                 => "left",
                    'quantity_color'                => "#212529ff",
                    'best_deal_color'               => "#fb0000ff",
                    'original_total_price_color'    => "#00aedaff",
                    'discount_total_price_color'    => "#546ea9ff",
                    'discount_badge_text_color'     => "#000000ff",
                    'discount_badge_background'     => "#f6f931ff",
                    'background_color'              => "#ffffffff",
                    'hover_background_color'        => "#f3f2ffff",
                    'container_background_color'    => "#ffffffff",
                    'quantity'                      => 1,
                    'discount'                      => 10,
                    'offer'                         => "% Off",
                    'bestdeal'                      => 0,
                ],
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
                'templates' => []
            ],
            [
                'name'      => env('UPSELLTYPE_NATIVE_POST_PURCHASE'),
                'image'     => '/img/post_purchase.png',
                'setting'   => [
                    "native_ppu_dicount_type"       => "% Off",
                    "native_ppu_dicount_value"      => "10",
                    "time_limit_toggler"            =>  1,
                    "time_limit_duration"           => "10",
                    "font_size"                     => "Small",
                    "text_align"                    => "Center",
                    "text_color"                    => "Red",
                    "bg_color_toggler"              => 1,
                    "border_color_toggler"          => 1,
                    "quantity_toggler"              => 1,
                    "variant_toggler"               => 1,
                    "desktop_view"                  => 1,
                    "mobile_view"                   => 1,
                    "user_welcome_msg"              => "Hey {customer.Name}",
                    "user_heading_font_size"        => "Large",
                    "user_heading_text_align"       => "Left",
                    "user_heading_text_color"       => "Green",
                    "text_tagline_message"          => "Hurry up before it sold out.",
                    "text_font_size"                => "Small",
                    "text_heading_align"            => "Left",
                    "text_heading_color"            => "Default",
                    "price_color"                   => "Default",
                    "compare_at_price_color"        => "Red",
                    "badge_color"                   => "Green",
                    "accept_offer_text"             => "Pay Now",
                    "decline_offer_text"            => "Decline this offer",
                    "start_date"                    => "2021-09-02",
                    "end_date"                      => null,
                    "native_post_purchase_heading"  => "This Exclusive offer Expire in:",
                ],
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
                'templates' => []
            ],
        ],
        'upsellTypeNamesToMatch' => explode(',',env('UPSELLTYPE_NAMES_TO_MATCH')),
        'postPurchaseUpsellName' => env('UPSELLTYPE_POST_PURCHASE'),
        'NativePostPurchaseUpsellName' => env('UPSELLTYPE_NATIVE_POST_PURCHASE'),
        'inCartUpsellName'       => env('UPSELLTYPE_IN_CART'),
        'sale_notification_identifier' => env('SALE_NOTIFICATION_IDENTIFIER'),
        'fontFamily' => [
            'Sans-Serif','Lato','Poppins','Fjalla','Arial','Verdana'
        ],
        'fontsize' => [
            'Auto','Large'
        ],
        'fbtLocation' => [
            'below_add_to_cart','below_the_description','below_the_product','bottom_of_page'
        ],
        'ppuDiscountType' => [
            '% Off','Fixed Price Off','No Discount'
        ],
        'animation' => [
            'Fade In','Bounce','Zoom','Shake'
        ],
        'font_weight' =>[
            'Normal','Bold','Bolder','Lighter'
        ],
        'layout_options' =>[
            'Rectangle Sales Popup','Round Sales Popup','Rounded Image Sales Popup'
        ],
        'pop_up_position' =>[
            'Bottom Left','Bottom Right','Top Left','Top Right'
        ],
        'text_align' => [
            'Center','Left','Right'
        ],
        'text_color' => [
            'Default','Red','Green','Yellow'
        ],
        'colorRegex' => '/^(#[a-fA-F0-9]{8})$/',
    ],
];
